### ISSUE TITLE
can't install on Mac

### ISSUE THREAD

**Issue by proukakis** [walaj/svaba#21] opened 2018-04-25 18:52 UTC
Hello 
I have tried on two macs running El Capitan
it fails after the "make" command

../../depcomp: line 611: /Users/christos/svaba/compile: No such file or directory
../../depcomp: line 611: exec: /Users/christos/svaba/compile: cannot execute: No such file or directory
make[2]: *** [libseqlib_a-ssw.o] Error 126
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

any suggestions?
thanks
christos

this is the whole output in case it helps
Christoss-MacBook:~ christos$ cd svaba
Christoss-MacBook:svaba christos$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/Users/christos/svaba/missing: Unknown `--is-lightweight' option
Try `/Users/christos/svaba/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc-5.3
checking whether we are using the GNU C compiler... no
checking whether gcc-5.3 accepts -g... no
checking for gcc-5.3 option to accept ISO C89... unsupported
checking whether gcc-5.3 understands -c and -o together... no
checking dependency style of /Users/christos/svaba/compile gcc-5.3... none
checking for ranlib... ranlib
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for library containing gzopen... -lz
checking for library containing clock_gettime... no
checking google/sparse_hash_set usability... no
checking google/sparse_hash_set presence... no
checking for google/sparse_hash_set... no
checking google/sparse_hash_map usability... no
checking google/sparse_hash_map presence... no
checking for google/sparse_hash_map... no
checking unordered_map usability... yes
checking unordered_map presence... yes
checking for unordered_map... yes
checking tr1/unordered_map usability... no
checking tr1/unordered_map presence... no
checking for tr1/unordered_map... no
checking ext/hash_map usability... yes
checking ext/hash_map presence... yes
checking for ext/hash_map... yes
checking unordered_set usability... yes
checking unordered_set presence... yes
checking for unordered_set... yes
checking tr1/unordered_set usability... no
checking tr1/unordered_set presence... no
checking for tr1/unordered_set... no
checking ext/hash_set usability... yes
checking ext/hash_set presence... yes
checking for ext/hash_set... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating SeqLib/src/Makefile
config.status: creating src/SGA/Util/Makefile
config.status: creating src/SGA/SQG/Makefile
config.status: creating src/SGA/Bigraph/Makefile
config.status: creating src/SGA/Algorithm/Makefile
config.status: creating src/SGA/StringGraph/Makefile
config.status: creating src/SGA/SuffixTools/Makefile
config.status: creating src/SGA/SGA/Makefile
config.status: creating src/svaba/Makefile
config.status: creating config.h
config.status: executing depfiles commands
Christoss-MacBook:svaba christos$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in SeqLib/fermi-lite
gcc -c -g -Wall -O2 -Wno-unused-function    kthread.c -o kthread.o
gcc -c -g -Wall -O2 -Wno-unused-function    misc.c -o misc.o
gcc -c -g -Wall -O2 -Wno-unused-function    bseq.c -o bseq.o
gcc -c -g -Wall -O2 -Wno-unused-function    htab.c -o htab.o
gcc -c -g -Wall -O2 -Wno-unused-function    bfc.c -o bfc.o
gcc -c -g -Wall -O2 -Wno-unused-function    rle.c -o rle.o
gcc -c -g -Wall -O2 -Wno-unused-function    rope.c -o rope.o
gcc -c -g -Wall -O2 -Wno-unused-function    mrope.c -o mrope.o
gcc -c -g -Wall -O2 -Wno-unused-function    rld0.c -o rld0.o
gcc -c -g -Wall -O2 -Wno-unused-function    unitig.c -o unitig.o
gcc -c -g -Wall -O2 -Wno-unused-function    mag.c -o mag.o
gcc -c -g -Wall -O2 -Wno-unused-function    bubble.c -o bubble.o
gcc -c -g -Wall -O2 -Wno-unused-function    f_ksw.c -o f_ksw.o
ar -csru libfml.a kthread.o misc.o bseq.o htab.o bfc.o rle.o rope.o mrope.o rld0.o unitig.o mag.o bubble.o f_ksw.o
gcc -c -g -Wall -O2 -Wno-unused-function    example.c -o example.o
gcc -g -Wall -O2 -Wno-unused-function  libfml.a example.o -o fml-asm -L. -lfml -lm -lz -lpthread
Making all in SeqLib/htslib
echo '/* Empty config.h generated by Makefile */' > config.h
gcc -g -Wall -O2 -I.  -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -I.  -c -o knetfile.o knetfile.c
gcc -g -Wall -O2 -I.  -c -o kstring.o kstring.c
gcc -g -Wall -O2 -I.  -c -o bgzf.o bgzf.c
gcc -g -Wall -O2 -I.  -c -o errmod.o errmod.c
gcc -g -Wall -O2 -I.  -c -o faidx.o faidx.c
gcc -g -Wall -O2 -I.  -c -o hfile.o hfile.c
gcc -g -Wall -O2 -I.  -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.3.2-147-g293a426"' > version.h
gcc -g -Wall -O2 -I.  -c -o hts.o hts.c
hts.c:51:5: warning: unused function 'ks_getc' [-Wunused-function]
    KSTREAM_INIT2(, BGZF*, bgzf_read, 65536)
    ^
./htslib/kseq.h:152:2: note: expanded from macro 'KSTREAM_INIT2'
        __KS_INLINED(__read)
        ^
./htslib/kseq.h:68:20: note: expanded from macro '__KS_INLINED'
        static inline int ks_getc(kstream_t *ks) \
                          ^
1 warning generated.
gcc -g -Wall -O2 -I.  -c -o md5.o md5.c
gcc -g -Wall -O2 -I.  -c -o probaln.o probaln.c
gcc -g -Wall -O2 -I.  -c -o realn.o realn.c
gcc -g -Wall -O2 -I.  -c -o regidx.o regidx.c
gcc -g -Wall -O2 -I.  -c -o sam.o sam.c
gcc -g -Wall -O2 -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -g -Wall -O2 -I.  -c -o vcf_sweep.o vcf_sweep.c
gcc -g -Wall -O2 -I.  -c -o tbx.o tbx.c
gcc -g -Wall -O2 -I.  -c -o thread_pool.o thread_pool.c
gcc -g -Wall -O2 -I.  -c -o vcf.o vcf.c
gcc -g -Wall -O2 -I.  -c -o vcfutils.o vcfutils.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_decode.o cram/cram_decode.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_external.o cram/cram_external.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_samtools.o cram/cram_samtools.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_stats.o cram/cram_stats.c
gcc -g -Wall -O2 -I.  -c -o cram/files.o cram/files.c
gcc -g -Wall -O2 -I.  -c -o cram/mFILE.o cram/mFILE.c
gcc -g -Wall -O2 -I.  -c -o cram/open_trace_file.o cram/open_trace_file.c
gcc -g -Wall -O2 -I.  -c -o cram/pooled_alloc.o cram/pooled_alloc.c
gcc -g -Wall -O2 -I.  -c -o cram/rANS_static.o cram/rANS_static.c
gcc -g -Wall -O2 -I.  -c -o cram/sam_header.o cram/sam_header.c
gcc -g -Wall -O2 -I.  -c -o cram/string_alloc.o cram/string_alloc.c
gcc -g -Wall -O2 -I.  -c -o cram/vlen.o cram/vlen.c
gcc -g -Wall -O2 -I.  -c -o cram/zfio.o cram/zfio.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bgzf.o errmod.o faidx.o hfile.o hfile_net.o hts.o md5.o probaln.o realn.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o thread_pool.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o cram/vlen.o cram/zfio.o
ranlib libhts.a
gcc -dynamiclib -install_name /usr/local/lib/libhts.2.dylib -current_version 1.3.255 -compatibility_version 2  -o libhts.dylib kfunc.o knetfile.o kstring.o bgzf.o errmod.o faidx.o hfile.o hfile_net.o hts.o md5.o probaln.o realn.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o thread_pool.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o cram/vlen.o cram/zfio.o -lz 
ln -sf libhts.dylib libhts.2.dylib
gcc -g -Wall -O2 -I.  -c -o bgzip.o bgzip.c
gcc -pthread  -o bgzip bgzip.o libhts.a -lz 
clang: warning: argument unused during compilation: '-pthread'
gcc -g -Wall -O2 -I.  -c -o htsfile.o htsfile.c
gcc -pthread  -o htsfile htsfile.o libhts.a -lz 
clang: warning: argument unused during compilation: '-pthread'
gcc -g -Wall -O2 -I.  -c -o tabix.o tabix.c
gcc -pthread  -o tabix tabix.o libhts.a -lz 
clang: warning: argument unused during compilation: '-pthread'
gcc -g -Wall -O2 -I.  -c -o test/fieldarith.o test/fieldarith.c
gcc -pthread  -o test/fieldarith test/fieldarith.o libhts.a -lz 
clang: warning: argument unused during compilation: '-pthread'
gcc -g -Wall -O2 -I.  -c -o test/hfile.o test/hfile.c
gcc -pthread  -o test/hfile test/hfile.o libhts.a -lz 
clang: warning: argument unused during compilation: '-pthread'
gcc -g -Wall -O2 -I.  -c -o test/sam.o test/sam.c
gcc -pthread  -o test/sam test/sam.o libhts.a -lz 
clang: warning: argument unused during compilation: '-pthread'
gcc -g -Wall -O2 -I.  -c -o test/test-regidx.o test/test-regidx.c
gcc -pthread  -o test/test-regidx test/test-regidx.o libhts.a -lz 
clang: warning: argument unused during compilation: '-pthread'
gcc -g -Wall -O2 -I.  -c -o test/test_view.o test/test_view.c
gcc -pthread  -o test/test_view test/test_view.o libhts.a -lz 
clang: warning: argument unused during compilation: '-pthread'
gcc -g -Wall -O2 -I.  -c -o test/test-vcf-api.o test/test-vcf-api.c
gcc -pthread  -o test/test-vcf-api test/test-vcf-api.o libhts.a -lz 
clang: warning: argument unused during compilation: '-pthread'
gcc -g -Wall -O2 -I.  -c -o test/test-vcf-sweep.o test/test-vcf-sweep.c
gcc -pthread  -o test/test-vcf-sweep test/test-vcf-sweep.o libhts.a -lz 
clang: warning: argument unused during compilation: '-pthread'
Making all in SeqLib/bwa
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  utils.c -o utils.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  kthread.c -o kthread.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  ksw.c -o ksw.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwt.c -o bwt.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bntseq.c -o bntseq.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwa.c -o bwa.o
bwa.c:147:18: warning: absolute value function 'abs' given an argument of type 'long long' but has parameter of
      type 'int' which may cause truncation of value [-Wabsolute-value]
                w = (max_gap + abs(rlen - l_query) + 1) >> 1;
                               ^
bwa.c:147:18: note: use function 'llabs' instead
                w = (max_gap + abs(rlen - l_query) + 1) >> 1;
                               ^~~
                               llabs
bwa.c:149:11: warning: absolute value function 'abs' given an argument of type 'long long' but has parameter of
      type 'int' which may cause truncation of value [-Wabsolute-value]
                min_w = abs(rlen - l_query) + 3;
                        ^
bwa.c:149:11: note: use function 'llabs' instead
                min_w = abs(rlen - l_query) + 3;
                        ^~~
                        llabs
2 warnings generated.
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwamem.c -o bwamem.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwamem_pair.c -o bwamem_pair.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwamem_extra.c -o bwamem_extra.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  malloc_wrap.c -o malloc_wrap.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  is.c -o is.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwtindex.c -o bwtindex.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  rope.c -o rope.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  rle.c -o rle.o
ar -csru libbwa.a utils.o kthread.o ksw.o bwt.o bntseq.o bwa.o bwamem.o bwamem_pair.o bwamem_extra.o malloc_wrap.o is.o bwtindex.o rope.o rle.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwashm.c -o bwashm.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwase.c -o bwase.o
bwase.c:181:57: warning: absolute value function 'abs' given an argument of type 'long long' but has parameter
      of type 'int' which may cause truncation of value [-Wabsolute-value]
        ksw_global(len, seq, rlen, rseq, 5, mat, 5, 1, SW_BW > abs(rlen - len) * 1.5? SW_BW : abs(rlen ...
                                                               ^
bwase.c:181:57: note: use function 'llabs' instead
        ksw_global(len, seq, rlen, rseq, 5, mat, 5, 1, SW_BW > abs(rlen - len) * 1.5? SW_BW : abs(rlen ...
                                                               ^~~
                                                               llabs
bwase.c:181:88: warning: absolute value function 'abs' given an argument of type 'long long' but has parameter
      of type 'int' which may cause truncation of value [-Wabsolute-value]
  ...seq, rlen, rseq, 5, mat, 5, 1, SW_BW > abs(rlen - len) * 1.5? SW_BW : abs(rlen - len) * 1.5, n_cigar, &...
                                                                           ^
bwase.c:181:88: note: use function 'llabs' instead
  ...seq, rlen, rseq, 5, mat, 5, 1, SW_BW > abs(rlen - len) * 1.5? SW_BW : abs(rlen - len) * 1.5, n_cigar, &...
                                                                           ^~~
                                                                           llabs
2 warnings generated.
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwaseqio.c -o bwaseqio.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwtgap.c -o bwtgap.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwtaln.c -o bwtaln.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bamlite.c -o bamlite.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwape.c -o bwape.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  kopen.c -o kopen.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  pemerge.c -o pemerge.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  maxk.c -o maxk.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwtsw2_core.c -o bwtsw2_core.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwtsw2_main.c -o bwtsw2_main.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwtsw2_aux.c -o bwtsw2_aux.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwt_lite.c -o bwt_lite.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwtsw2_chain.c -o bwtsw2_chain.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  fastmap.c -o fastmap.o
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  bwtsw2_pair.c -o bwtsw2_pair.o
bwtsw2_pair.c:239:13: warning: using floating point absolute value function 'fabs' when argument is of integer
      type [-Wabsolute-value]
                                        diff = fabs(G[0] - G[1]) / (opt->a + opt->b) / ((hits[i]->hits[...
                                               ^
bwtsw2_pair.c:239:13: note: use function 'abs' instead
                                        diff = fabs(G[0] - G[1]) / (opt->a + opt->b) / ((hits[i]->hits[...
                                               ^~~~
                                               abs
1 warning generated.
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  main.c -o main.o
gcc -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS bwashm.o bwase.o bwaseqio.o bwtgap.o bwtaln.o bamlite.o bwape.o kopen.o pemerge.o maxk.o bwtsw2_core.o bwtsw2_main.o bwtsw2_aux.o bwt_lite.o bwtsw2_chain.o fastmap.o bwtsw2_pair.o main.o -o bwa -L. -lbwa -lm -lz -lpthread
Making all in SeqLib/src
g++ -DHAVE_CONFIG_H -I. -I../..  -I../ -I../htslib -Wno-sign-compare  -g -Wall -Wextra  -Wno-unknown-pragmas -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -g -O2 -MT libseqlib_a-FastqReader.o -MD -MP -MF .deps/libseqlib_a-FastqReader.Tpo -c -o libseqlib_a-FastqReader.o `test -f 'FastqReader.cpp' || echo './'`FastqReader.cpp
mv -f .deps/libseqlib_a-FastqReader.Tpo .deps/libseqlib_a-FastqReader.Po
g++ -DHAVE_CONFIG_H -I. -I../..  -I../ -I../htslib -Wno-sign-compare  -g -Wall -Wextra  -Wno-unknown-pragmas -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -g -O2 -MT libseqlib_a-BFC.o -MD -MP -MF .deps/libseqlib_a-BFC.Tpo -c -o libseqlib_a-BFC.o `test -f 'BFC.cpp' || echo './'`BFC.cpp
mv -f .deps/libseqlib_a-BFC.Tpo .deps/libseqlib_a-BFC.Po
g++ -DHAVE_CONFIG_H -I. -I../..  -I../ -I../htslib -Wno-sign-compare  -g -Wall -Wextra  -Wno-unknown-pragmas -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -g -O2 -MT libseqlib_a-ReadFilter.o -MD -MP -MF .deps/libseqlib_a-ReadFilter.Tpo -c -o libseqlib_a-ReadFilter.o `test -f 'ReadFilter.cpp' || echo './'`ReadFilter.cpp
mv -f .deps/libseqlib_a-ReadFilter.Tpo .deps/libseqlib_a-ReadFilter.Po
g++ -DHAVE_CONFIG_H -I. -I../..  -I../ -I../htslib -Wno-sign-compare  -g -Wall -Wextra  -Wno-unknown-pragmas -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -g -O2 -MT libseqlib_a-SeqPlot.o -MD -MP -MF .deps/libseqlib_a-SeqPlot.Tpo -c -o libseqlib_a-SeqPlot.o `test -f 'SeqPlot.cpp' || echo './'`SeqPlot.cpp
mv -f .deps/libseqlib_a-SeqPlot.Tpo .deps/libseqlib_a-SeqPlot.Po
g++ -DHAVE_CONFIG_H -I. -I../..  -I../ -I../htslib -Wno-sign-compare  -g -Wall -Wextra  -Wno-unknown-pragmas -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -g -O2 -MT libseqlib_a-jsoncpp.o -MD -MP -MF .deps/libseqlib_a-jsoncpp.Tpo -c -o libseqlib_a-jsoncpp.o `test -f 'jsoncpp.cpp' || echo './'`jsoncpp.cpp
mv -f .deps/libseqlib_a-jsoncpp.Tpo .deps/libseqlib_a-jsoncpp.Po
g++ -DHAVE_CONFIG_H -I. -I../..  -I../ -I../htslib -Wno-sign-compare  -g -Wall -Wextra  -Wno-unknown-pragmas -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -g -O2 -MT libseqlib_a-ssw_cpp.o -MD -MP -MF .deps/libseqlib_a-ssw_cpp.Tpo -c -o libseqlib_a-ssw_cpp.o `test -f 'ssw_cpp.cpp' || echo './'`ssw_cpp.cpp
ssw_cpp.cpp:449:19: warning: unused parameter 'score_matrix_size' [-Wunused-parameter]
    const int&    score_matrix_size,
                  ^
1 warning generated.
mv -f .deps/libseqlib_a-ssw_cpp.Tpo .deps/libseqlib_a-ssw_cpp.Po
source='ssw.c' object='libseqlib_a-ssw.o' libtool=no \
	DEPDIR=.deps depmode=none /bin/sh ../../depcomp \
	/Users/christos/svaba/compile gcc-5.3 -DHAVE_CONFIG_H -I. -I../..  -I../ -I../htslib -Wno-sign-compare    -c -o libseqlib_a-ssw.o `test -f 'ssw.c' || echo './'`ssw.c
../../depcomp: line 611: /Users/christos/svaba/compile: No such file or directory
../../depcomp: line 611: exec: /Users/christos/svaba/compile: cannot execute: No such file or directory
make[2]: *** [libseqlib_a-ssw.o] Error 126
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by walaj** [comment] 2018-04-26 17:14
Thanks for reporting, I'm not sure what is going on. It looks like the problem is the SeqLib compilation. Can you try compiling SeqLib? I am not able to recreate on my Mac but I agree from your output there is an issue here.

https://github.com/walaj/SeqLib

**Comment by proukakis** [comment] 2018-04-26 17:43
thanks, you re right, i cant compile this

 (same result if I use simply "make")

make  CC=gcc-7 CXX=g++-7
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
/bin/sh: sed: command not found
Making  in bwa
make[2]: execvp: uname: Invalid argument
gcc-7 -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  utils.c -o utils.o
make[2]: gcc-7: No such file or directory
make[2]: *** [utils.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2


I dont know if there is something wrong with my path, entirely possible as I have been messing around, will have a think and try another mac
christos

**Comment by walaj** [comment] 2018-04-27 01:43
Ahh, yes having a bad ``PATH`` will be a problem. I see you don't even have the ability run ``sed``. I'll close this since I don't think this is a svaba issue. You can re-open if you find an issue that is on my end. For what it's worth, I can compile without any issue on multiple difference macs.

**Closed by walaj** 2018-04-27 01:43 UTC

**Comment by proukakis** [comment] 2018-04-27 11:01
yes, I eventually worked out the correct path after miniconda had messed it up, all is fine, thanks!
